# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passworduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email confirmed'),
        ),
    ]
