# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_availablestreet_location'),
        ('users', '0003_appuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.Location', verbose_name='Location'),
        ),
    ]
