# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 05:48
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
                ('icon', models.FileField(upload_to=core.utils.upload_path_handler, verbose_name='icon')),
                ('color', models.CharField(default='', help_text='example: #651fff', max_length=8, verbose_name='color hex')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='', max_length=512, verbose_name='name')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='', verbose_name='icon')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.IntegerField(verbose_name='object id')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=core.utils.upload_path_handler, verbose_name='image')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='object name')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='', max_length=512, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('ingredients', models.CharField(default='', max_length=1024, verbose_name='ingredients')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='old price')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Action', verbose_name='action')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Category', verbose_name='category')),
                ('specials', models.ManyToManyField(blank=True, related_name='_product_specials_+', to='catalog.Product', verbose_name='specials')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='', max_length=512, verbose_name='name')),
                ('short_name', models.CharField(default='', help_text='would be used in specials', max_length=512, verbose_name='short name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='price')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.Product', verbose_name='product')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='product'),
        ),
    ]
