# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170709_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='notes',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='would be used in specials', max_length=512, verbose_name='short name'),
        ),
    ]
