# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170727_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'action Translation',
                'db_table': 'catalog_action_translation',
                'default_permissions': (),
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'product category Translation',
                'db_table': 'catalog_category_translation',
                'default_permissions': (),
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, default='', max_length=512, verbose_name='name')),
                ('short_name', models.CharField(blank=True, default='', help_text='would be used in specials', max_length=512, verbose_name='short name')),
            ],
            options={
                'verbose_name': 'price Translation',
                'db_table': 'catalog_productprice_translation',
                'default_permissions': (),
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=512, verbose_name='name')),
                ('ingredients', models.CharField(default='', max_length=1024, verbose_name='ingredients')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'catalog_product_translation',
                'default_permissions': (),
                'managed': True,
                'db_tablespace': '',
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='short_name',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='productpricetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.ProductPrice'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='actiontranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.Action'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='productpricetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='actiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
