# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170818_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
