# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20170819_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_bottom_menu',
            field=models.BooleanField(default=True, verbose_name='show on bottom menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_top_menu',
            field=models.BooleanField(default=True, verbose_name='show on top menu'),
        ),
    ]
