# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 05:48
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=512, verbose_name='username')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, verbose_name='phone')),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'delivery'), ('PICKUP', 'pickup')], default='DELIVERY', max_length=12, verbose_name='delivery type')),
                ('address_type', models.CharField(choices=[('ADDRESS', 'address'), ('ARENA', 'arena')], default='ADDRESS', max_length=12, verbose_name='type')),
                ('street', models.CharField(blank=True, default='', max_length=1024, verbose_name='street')),
                ('house', models.CharField(blank=True, default='', max_length=512, verbose_name='house')),
                ('landmark', models.CharField(blank=True, default='', max_length=1024, verbose_name='landmark')),
                ('arena', models.CharField(blank=True, default='', max_length=1024, verbose_name='arena')),
                ('tribune', models.PositiveIntegerField(default=0, verbose_name='tribune')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='row number')),
                ('col_number', models.PositiveIntegerField(default=0, verbose_name='col number')),
                ('comment', models.TextField(blank=True, default='', verbose_name='house')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('token', models.CharField(default=core.utils.generate_token, editable=False, max_length=512, verbose_name='token')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'cart items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('WAIT', 'wait'), ('CONFIRMED', 'confirmed'), ('PROGRESS', 'progress'), ('DELIVERY', 'delivery')], default='WAIT', max_length=32, verbose_name='status')),
                ('address', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Address')),
                ('cart', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.Cart', verbose_name='cart')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
