# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:34
from __future__ import unicode_literals

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170704_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('WAIT', 'wait'), ('CONFIRMED', 'confirmed'), ('PROGRESS', 'progress'), ('DELIVERY', 'delivery'), ('CANCELED', 'canceled')], default='WAIT', max_length=32, verbose_name='status'),
        ),
    ]
