# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170708_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('WAIT', 'wait'), ('CONFIRMED', 'confirmed'), ('PROGRESS', 'progress'), ('DELIVERY', 'delivery'), ('CANCELED', 'canceled'), ('DONE', 'done')], default='NEW', max_length=32, verbose_name='status'),
        ),
    ]
