# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20170709_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
    ]
