# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20170710_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_status',
            field=models.CharField(choices=[('', 'null'), ('CREATED', 'created'), ('PAID', 'paid'), ('FAIL', 'fail'), ('SUCCESS', 'success')], default='', max_length=16, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ON_DELIVERY', 'on delivery'), ('ONLINE', 'online')], default='ON_DELIVERY', max_length=16, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='order',
            name='sb_form_url',
            field=models.CharField(blank=True, default='', editable=False, max_length=2048, verbose_name='sb form url'),
        ),
        migrations.AddField(
            model_name='order',
            name='sb_order_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=128, verbose_name='sb order id'),
        ),
    ]
