# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20170715_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sb_order_id',
            new_name='sb_remote_id',
        ),
        migrations.AddField(
            model_name='order',
            name='sb_internal_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=512, verbose_name='internal order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='online_status',
            field=models.CharField(default='', max_length=16, verbose_name='payment status'),
        ),
    ]
