# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20170716_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='online_status',
            field=models.IntegerField(default=None, max_length=16, null=True, verbose_name='payment status'),
        ),
    ]
