# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20170716_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='online_status',
            field=models.IntegerField(choices=[(None, 'null'), (0, "registered and didn't paid"), (1, 'amount was hold'), (2, 'success'), (3, 'auth cancelled'), (4, 'amount returned'), (5, 'initialized by emitent'), (6, 'auth rejected')], default=None, null=True, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('WAIT', 'wait'), ('FAILED', 'failed'), ('CONFIRMED', 'confirmed'), ('PROGRESS', 'progress'), ('DELIVERY', 'delivery'), ('CANCELED', 'canceled'), ('DONE', 'done')], default='NEW', max_length=32, verbose_name='status'),
        ),
    ]
