# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20170727_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sb_started_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='sb created at'),
        ),
    ]
