# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170924_0925'),
        ('cart', '0015_order_sb_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='expired at'),
        ),
    ]
