# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:07
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170706_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_timeout',
            field=models.PositiveIntegerField(default=0, help_text='order creation time', verbose_name='order minutes'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='header title'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(upload_to=core.utils.upload_path_handler, verbose_name='icon'),
        ),
    ]
