# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170709_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('active_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='active from')),
                ('active_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='active until')),
                ('title', models.CharField(default='', max_length=1024, verbose_name='title')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='picture')),
                ('text', models.TextField(default='', verbose_name='text')),
            ],
            options={
                'ordering': ['-active_from'],
                'verbose_name_plural': 'actions',
                'verbose_name': 'action',
            },
        ),
    ]
