# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='metric_code',
            field=models.TextField(blank=True, default='', verbose_name='metric code'),
        ),
    ]
