# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 18:11
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteconfiguration_metric_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.upload_path_handler, verbose_name='image')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'slider image',
                'verbose_name_plural': 'slider images',
                'ordering': ('-position',),
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='metric_code',
            field=models.TextField(blank=True, default='', help_text='yandex/google metric', verbose_name='metric code'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='core.SiteConfiguration', verbose_name='config'),
        ),
    ]
