# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170807_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ('position',), 'verbose_name': 'slider image', 'verbose_name_plural': 'slider images'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='arena_allowed',
            field=models.BooleanField(default=False, verbose_name='delivery to arena is allowed'),
        ),
    ]
