# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170813_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigurationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.CharField(blank=True, default='', max_length=1024, verbose_name='address')),
            ],
            options={
                'verbose_name': 'site config Translation',
                'managed': True,
                'db_tablespace': '',
                'db_table': 'core_siteconfiguration_translation',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address',
        ),
        migrations.AddField(
            model_name='siteconfigurationtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.SiteConfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='siteconfigurationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
