# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170816_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_comment',
        ),
        migrations.AddField(
            model_name='siteconfigurationtranslation',
            name='address_comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='address comment'),
        ),
    ]
