# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170816_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='metric_code',
            field=models.TextField(blank=True, default='', help_text='yandex/google metric', verbose_name='yandex/google metric'),
        ),
    ]
