# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_availablestreet'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='work_day_ended_at',
            field=models.TimeField(default='23:00', verbose_name='work day ended at'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='work_day_started_at',
            field=models.TimeField(default='09:00', verbose_name='work day started at'),
        ),
    ]
