# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteconfiguration_order_phone_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='order_phone_notification',
            field=models.CharField(default='', max_length=16, verbose_name='phone notification'),
        ),
    ]
