# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170818_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableStreetTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name1', models.CharField(default='', max_length=2014, verbose_name='street name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.AvailableStreet')),
            ],
            options={
                'verbose_name': 'available street Translation',
                'db_table': 'core_availablestreet_translation',
                'managed': True,
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.AlterUniqueTogether(
            name='availablestreettranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
