# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170818_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablestreet',
            name='name',
        ),
    ]
