# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_availablestreet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablestreettranslation',
            old_name='name1',
            new_name='name',
        ),
    ]
