# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_availablestreet_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='notification_is_enabled',
            field=models.BooleanField(default=True, verbose_name='notification is enabled'),
        ),
    ]
