# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170923_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'site config', 'verbose_name_plural': 'sites config'},
        ),
    ]
