# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170924_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablestreet',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='location'),
        ),
    ]
