# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_availablestreet_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='order_phone_notification',
            new_name='order_telegram_notification_channel',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='notification_is_enabled',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notification_phone_is_enabled',
            field=models.BooleanField(default=True, verbose_name='phone notification is enabled'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notification_telegram_is_enabled',
            field=models.BooleanField(default=True, verbose_name='telegram notifications is enabled'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_phone_notification_number',
            field=models.CharField(default='', max_length=16, verbose_name='telegram notification'),
        ),
    ]
