# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170929_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='schedule',
        ),
        migrations.AddField(
            model_name='siteconfigurationtranslation',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='schedule'),
        ),
    ]
