# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20170929_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='yandex_delivery_area',
            field=models.TextField(default='', verbose_name='Yandex delivery area'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='yandex_map_coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[43.410262, 39.9695], verbose_name='Yandex map coordinates'),
        ),
    ]
