# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20170929_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigurationtranslation',
            name='bottom_right_banner_text',
            field=models.TextField(default='', verbose_name="Bottom banner's text"),
        ),
    ]
