# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_siteconfiguration_bottom_right_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='bottom_right_banner_icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name="Bottom banner's icon"),
        ),
    ]
