# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_siteconfiguration_bottom_right_banner_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='min_order_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='min order sumw'),
        ),
    ]
